var newQ = 'number'+ 3 + 3
console.log (newQ)


var newA = null + 3;
console.log (newA)

var newS = 5 && "qwerty"
console.log (newS)

var newH = +'40' + +'2' + "hillel";
console.log (newH)

var newC = '10' - 5 === 6;
console.log (newC)

var newT = true + false;
console.log (true + false)

var newT = '4px' - 3;
console.log (newT)

var newY = '4' - 3; 
console.log (newY)

var newO = '6' + 3 ** 0;
console.log (newO)


